<?php

namespace restBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * vote_ideeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vote_ideeRepository extends EntityRepository
{
}
