<?php

namespace restBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * vote_commentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vote_commentaireRepository extends EntityRepository
{
}
