rest_user_add:
    path:     /utilisateur
    defaults: { _controller: restBundle:Utilisateur:add }
    methods:  [POST]

rest_user_get:
    path:     /utilisateur
    defaults: { _controller: restBundle:Utilisateur:get }
    methods:  [GET]

rest_user_delete:
    path:     /utilisateur
    defaults: { _controller: restBundle:Utilisateur:delete }
    methods:  [DELETE]