rest_user_add:
    path:     /utilisateur
    defaults: { _controller: restBundle:Utilisateur:add }
    methods:  [POST]

rest_user_get:
    path:     /utilisateur
    defaults: { _controller: restBundle:Utilisateur:get }
    methods:  [GET]

rest_user_delete:
    path:     /utilisateur
    defaults: { _controller: restBundle:Utilisateur:delete }
    methods:  [DELETE]

rest_user_update:
    path:     /utilisateur
    defaults: { _controller: restBundle:Utilisateur:update }
    methods:  [PUT]

rest_idee_add:
    path:     /idee
    defaults: { _controller: restBundle:Idee:add }
    methods:  [POST]

rest_idee_get:
    path:     /idee
    defaults: { _controller: restBundle:Idee:get }
    methods:  [GET]

rest_idee_delete:
    path:     /idee
    defaults: { _controller: restBundle:Idee:delete }
    methods:  [DELETE]

rest_idee_update:
    path:     /idee
    defaults: { _controller: restBundle:Idee:update }
    methods:  [PUT]

rest_commentaire_add:
    path:     /commentaire
    defaults: { _controller: restBundle:Commentaire:add }
    methods:  [POST]

rest_commentaire_get:
    path:     /commentaire
    defaults: { _controller: restBundle:Commentaire:get }
    methods:  [GET]

rest_commentaire_delete:
    path:     /commentaire
    defaults: { _controller: restBundle:Commentaire:delete }
    methods:  [DELETE]

rest_commentaire_update:
    path:     /commentaire
    defaults: { _controller: restBundle:Commentaire:update }
    methods:  [PUT]

rest_vote_commentaire_add:
    path:     /vote_commentaire
    defaults: { _controller: restBundle:Vote_Commentaire:add }
    methods:  [POST]

rest_vote_commentaire_delete:
    path:     /vote_commentaire
    defaults: { _controller: restBundle:Vote_Commentaire:delete }
    methods:  [DELETE]

rest_vote_idee_add:
    path:     /vote_idee
    defaults: { _controller: restBundle:Vote_Idee:add }
    methods:  [POST]

rest_vote_idee_delete:
    path:     /vote_idee
    defaults: { _controller: restBundle:Vote_Idee:delete }
    methods:  [DELETE]
